version: '3.7'
services:
  web:
    container_name: project_web
    build:
      context: ./.docker
      dockerfile: web.docker
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
    links:
      - app
  app:
    container_name: project_app
    build:
      context: ./.docker
      dockerfile: app.docker
    volumes:
      - ./:/var/www
    links:
      - database
  database:
      container_name: project_database
      image: mysql:latest
      environment:
        - "MYSQL_ROOT_PASSWORD=root"
        - "MYSQL_USER=homestead"
        - "MYSQL_DATABASE=homestead"
        - "MYSQL_PASSWORD=secret"
      volumes:
        - database:/var/lib/mysql
volumes:
  database:
    driver: local
