version: '2'
services:
  web:
    build:
      context: ./docker
      dockerfile: web.docker
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
    links:
      - app
  app:
    build:
      context: ./docker
      dockerfile: app.docker
    volumes:
      - ./:/var/www
    links:
      - database
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
  database:
      image: mariadb:10.3
      environment:
        - "MYSQL_ROOT_PASSWORD=root"
        - "MYSQL_USER=homestead"
        - "MYSQL_DATABASE=homestead"
        - "MYSQL_PASSWORD=secret"
      volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
    driver: local
